/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package surveys;

import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import static surveys.Surveys.qry;
import static surveys.Surveys.rs;
import static surveys.Surveys.statement;

/**
 *
 * @author Indu
 */
public class Chart extends javax.swing.JFrame {

    private boolean load=true;

    /**
     * Creates new form Chart
     */
    public Chart() throws SQLException {
        initComponents();
        qry= "select  distinct category from mst_survey";
        System.out.print(qry);
        rs = statement.executeQuery(qry);
        cat_combo.removeAllItems();
        cat_combo.addItem("Select Category");
        while (rs.next())
        {
            cat_combo.addItem(rs.getString("category"));
        }
        lblcat.setVisible(false);
        lbltitle.setVisible(false);
        cat_combo.setVisible(false);
        title_combo.setVisible(false);
        btngraph.setVisible(false);
        
        load=false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btngraph = new javax.swing.JButton();
        btnno = new javax.swing.JButton();
        cat_combo = new javax.swing.JComboBox<>();
        lblcat = new javax.swing.JLabel();
        title_combo = new javax.swing.JComboBox<>();
        lbltitle = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));

        btngraph.setText("Make Graph");
        btngraph.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btngraphMouseClicked(evt);
            }
        });
        btngraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngraphActionPerformed(evt);
            }
        });

        btnno.setText("Export");
        btnno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(826, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btngraph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addComponent(btngraph)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnno)
                .addGap(66, 66, 66))
        );

        cat_combo.setBackground(new java.awt.Color(102, 102, 102));
        cat_combo.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        cat_combo.setForeground(new java.awt.Color(255, 255, 255));
        cat_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cat_combo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cat_combo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cat_combo.setName(""); // NOI18N
        cat_combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cat_comboItemStateChanged(evt);
            }
        });
        cat_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cat_comboActionPerformed(evt);
            }
        });

        lblcat.setBackground(new java.awt.Color(0, 0, 0));
        lblcat.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        lblcat.setText("Category");

        title_combo.setBackground(new java.awt.Color(102, 102, 102));
        title_combo.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        title_combo.setForeground(new java.awt.Color(255, 255, 255));
        title_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        title_combo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        title_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                title_comboActionPerformed(evt);
            }
        });

        lbltitle.setBackground(new java.awt.Color(0, 0, 0));
        lbltitle.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        lbltitle.setText("Title");

        jMenu1.setText("Number of Surveys Conducted");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Individual Survey Analysis");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 938, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcat)
                    .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cat_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cat_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btngraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngraphActionPerformed
       IndSurvey();
    }//GEN-LAST:event_btngraphActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        lblcat.setVisible(false);
        lbltitle.setVisible(false);
        cat_combo.setVisible(false);
        title_combo.setVisible(false);
        btngraph.setVisible(false);
        
        NoSurveys();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void cat_comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cat_comboItemStateChanged
        if (load==false)
        {
            try
            {
                qry= "select  * from mst_survey where category='" + cat_combo.getSelectedItem() + "'";
                System.out.println(qry);
                rs = statement.executeQuery(qry);

                title_combo.removeAllItems();
                while (rs.next())
                {
                    title_combo.addItem(rs.getString("title"));
                }

            }
            catch(SQLException ex)
            {
            }
        }
    }//GEN-LAST:event_cat_comboItemStateChanged

    private void cat_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cat_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cat_comboActionPerformed

    private void title_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_title_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_title_comboActionPerformed

    private void btngraphMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngraphMouseClicked
       IndSurvey();
    }//GEN-LAST:event_btngraphMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        lblcat.setVisible(true);
        lbltitle.setVisible(true);
        cat_combo.setVisible(true);
        title_combo.setVisible(true);
        btngraph.setVisible(true);
        
       
    }//GEN-LAST:event_jMenu2MouseClicked

    private void btnnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnoActionPerformed

        try {
            int width=1000; /* Width of the image */
            int height=1000; /* Height of the image */
            File BarChart=new File("C:\\Users\\Indu\\Downloads\\output_chart.png");
            ChartUtilities.saveChartAsPNG(BarChart,BarChartObject,width,height);
            JOptionPane.showMessageDialog(null,"File Saved to " + BarChart.getPath());
        } catch (IOException ex) {
            Logger.getLogger(Chart.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_btnnoActionPerformed

    /**
     * @param args the command line arguments
     */
    JFreeChart BarChartObject;
    ChartPanel panel ;
    public static void main(String args[]) {
        
    }
      
    private void NoSurveys()
    {
        try
        {
        DefaultCategoryDataset my_bar_chart_dataset = new DefaultCategoryDataset();
        
                        rs = statement.executeQuery("select category,count(distinct tbl_ans.surveyid)cnt  from mst_survey left join tbl_ans on mst_survey.surveyid=tbl_ans.surveyid group by category");
                        while (rs.next()) {
                                String category = rs.getString("category");
                                int cnt = rs.getInt("cnt");
                                my_bar_chart_dataset.addValue(cnt,"Category",category);
                                
                                }
                        
                 BarChartObject=ChartFactory.createBarChart("Category wise Surveys","Category","No of Surveys",my_bar_chart_dataset,PlotOrientation.VERTICAL,true,true,false);                  
                          
                    
                CategoryPlot p = BarChartObject.getCategoryPlot();

         //p.setRangeGridlinePaint(Color.BLUE);

                 
                panel = new ChartPanel(BarChartObject);
                panel.setVisible(true);
                panel.setSize(300 ,300);
                jPanel1.add(panel);
                 validate();
                repaint();                
                //survey_table.setModel(DbUtils.resultSetToTableModel(rs));
                 
        }
        catch (SQLException i)
        {
        System.out.println(i);
        }
    }
        
    private void IndSurvey()
    {
        try
        {
        panel.repaint();
        panel.validate();
        DefaultCategoryDataset my_bar_chart_dataset = new DefaultCategoryDataset();
        qry="select * from mst_survey where Title='" + title_combo.getSelectedItem() + "' and Category='" + cat_combo.getSelectedItem() +"'";
        rs = statement.executeQuery(qry);
        rs.next();
        String surveyid=rs.getString("surveyid");
        
        rs = statement.executeQuery("SELECT ques,sum(LEFT(answer,1))cnt FROM mst_ques LEFT JOIN tbl_ans ON mst_ques.surveyid=tbl_ans.surveyid AND  mst_ques.quesno=tbl_ans.quesno WHERE mst_ques.surveyid='" + surveyid + "' GROUP BY ques;");
        while (rs.next()) {
                String category = rs.getString("ques");
                int cnt = rs.getInt("cnt");
                my_bar_chart_dataset.addValue(cnt,"ques",category);
                }            
                BarChartObject=ChartFactory.createBarChart("Individual Analysis","Question","Score",my_bar_chart_dataset,PlotOrientation.VERTICAL,true,true,false);                         
                panel = new ChartPanel(BarChartObject);
                panel.setVisible(true);
                panel.setSize(800 ,300);                
                jPanel1.add(panel);               
                validate();
                repaint();                
        }
        catch (SQLException i)
        {
        System.out.println(i);
        }
 

    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngraph;
    private javax.swing.JButton btnno;
    private javax.swing.JComboBox<String> cat_combo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblcat;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JComboBox<String> title_combo;
    // End of variables declaration//GEN-END:variables
}
