/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package surveys;

/**
 *
 * @author Harshita
 */
import java.sql.DriverManager;
import java.sql.Statement;  
import java.sql.ResultSet;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class SurveyDefine extends javax.swing.JFrame {

    /**
     * Creates new form SurveyDefine
     */
    public SurveyDefine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        survey_title = new javax.swing.JLabel();
        survey_category = new javax.swing.JLabel();
        title_text = new javax.swing.JTextField();
        category_options = new javax.swing.JComboBox<>();
        save_button = new javax.swing.JButton();
        question_label = new javax.swing.JLabel();
        questext = new javax.swing.JTextField();
        quessavebutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        survey_table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPanel1FocusLost(evt);
            }
        });

        survey_title.setText("TITLE");

        survey_category.setText("CATEGORY");

        category_options.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Health", "Education", "Fashion", "Item 5", "Item 6" }));

        save_button.setText("SAVE");
        save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_buttonActionPerformed(evt);
            }
        });

        question_label.setText("Ques");

        questext.setText("question_text");

        quessavebutton.setText("save");
        quessavebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quessavebuttonActionPerformed(evt);
            }
        });

        survey_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "SurveyID", "Title", "Category"
            }
        ));
        jScrollPane1.setViewportView(survey_table);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(survey_title, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(survey_category, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(category_options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title_text, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(question_label, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(questext, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(save_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(quessavebutton)
                        .addGap(91, 91, 91)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(question_label)
                        .addComponent(questext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(category_options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(survey_category))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(survey_title)
                            .addComponent(title_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(save_button)
                            .addComponent(quessavebutton)
                            .addComponent(jButton1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    static String ID = "";
    private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_buttonActionPerformed
        try{
            java.sql.Connection conn = null;
            String qry="select * from mst_survey where Title='" + title_text.getText() + "' and Category='" + category_options.getSelectedItem() +"'";
            System.out.println(qry);
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/survey","root","");
            Statement statement = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);  
            
            ResultSet rs = statement.executeQuery(qry);
            rs.next();
            if (rs.getRow()==0){
                ID = generateID(6);
                qry= "INSERT INTO mst_survey(SurveyID,Title,Category) VALUES('"+ID+"','"+title_text.getText()+ "','" + category_options.getSelectedItem()+"')";
                System.out.println(qry);
                statement.executeUpdate(qry);  
                
                JOptionPane.showMessageDialog(null,"saved successfully");
                qry= "select * from mst_survey";
                rs = statement.executeQuery(qry);
                DefaultTableModel dtm = new DefaultTableModel();
                Object [] rowData = new Object[3];
                
                //survey_table.setModel(DbUtils.resultSetToTableModel(rs));
                while (rs.next()){
                
                   for (int col=1; col<=2;col++)
                   {
                        rowData[col] = rs.getObject(col);                       
                    }
                    
                    dtm.addRow(rowData);
                    System.out.println(dtm.getRowCount());
                    survey_table.setModel(dtm);
                    //dtm.addRow(new Object[] { "SurveyID", "Title", "Category"});
                    
                }
                
 
            }
    
             else
            {
                JOptionPane.showMessageDialog(null,"Duplicate Survey!!");  
                //SendMailSSL sm=new SendMailSSL();
                //sm.send();
                this.setVisible(false);
                //new survey_form().setVisible(true);
                new SurveyDefine().setVisible(true);
            }
            //Referesh(); //Calling Referesh() method  
        // catch (SQLException | ClassNotFoundException e) 
         //{  
          //  JOptionPane.showMessageDialog(null, e); 
          
           
            // JOptionPane.showMessageDialog(null, "Record inserted...");  
            statement.close();  
            conn.close();  
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_save_buttonActionPerformed

    private void quessavebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quessavebuttonActionPerformed
        try{
            java.sql.Connection conn = null;
            String qry="select * from mst_ques where surveyid='" + ID + "' and ques='" + questext.getText()+"'";
            System.out.println(qry);
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/survey","root","");
            Statement statement = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);  
            
            ResultSet rs = statement.executeQuery(qry);
            rs.next();
            if (rs.getRow()==0){
                qry= "INSERT INTO mst_ques(SurveyID,ques) VALUES('"+ ID+ "','" + questext.getText()+"')";
                System.out.println(qry);
                statement.executeUpdate(qry);
                
                JOptionPane.showMessageDialog(null,"saved successfully!");
                questext.setText("");
            }
    
             else
            {
                JOptionPane.showMessageDialog(null,"Duplicate Question!!");  
                //SendMailSSL sm=new SendMailSSL();
                //sm.send();
                this.setVisible(false);
                //new survey_form().setVisible(true);
                new SurveyDefine().setVisible(true);
            }
            //Referesh(); //Calling Referesh() method  
        // catch (SQLException | ClassNotFoundException e) 
         //{  
          //  JOptionPane.showMessageDialog(null, e); 
          
           
            // JOptionPane.showMessageDialog(null, "Record inserted...");  
            statement.close();  
            conn.close();  
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
                                              

    }//GEN-LAST:event_quessavebuttonActionPerformed

    private void jPanel1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusLost
       
    }//GEN-LAST:event_jPanel1FocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         this.setVisible(false);
        new frame().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SurveyDefine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SurveyDefine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SurveyDefine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SurveyDefine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SurveyDefine().setVisible(true);
            }
        });
    }
    private static String generateID(int length) {
      String capitalCaseLetters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
      String lowerCaseLetters = "abcdefghijklmnopqrstuvwxyz";
      String specialCharacters = "!@#$";
      String numbers = "1234567890";
      String combinedChars = capitalCaseLetters + lowerCaseLetters + specialCharacters + numbers;
      Random random = new Random();
      String ID="";

      ID= ID+ lowerCaseLetters.charAt(random.nextInt(lowerCaseLetters.length()));
      ID = ID+capitalCaseLetters.charAt(random.nextInt(capitalCaseLetters.length()));
      ID = ID+specialCharacters.charAt(random.nextInt(specialCharacters.length()));
      ID = ID+numbers.charAt(random.nextInt(numbers.length()));
   
      for(int i = 4; i< length ; i++) {
         ID = ID+combinedChars.charAt(random.nextInt(combinedChars.length()));
      }
      return ID;
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> category_options;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton quessavebutton;
    private javax.swing.JTextField questext;
    private javax.swing.JLabel question_label;
    private javax.swing.JButton save_button;
    private javax.swing.JLabel survey_category;
    private javax.swing.JTable survey_table;
    private javax.swing.JLabel survey_title;
    private javax.swing.JTextField title_text;
    // End of variables declaration//GEN-END:variables
}
